### ISSUE TITLE
Start an incorporated society that is also a charity

### ISSUE THREAD

**Issue by ahdinosaur** [whacknz/whack#3]
- https://is-register.companiesoffice.govt.nz/help-centre/starting-an-incorporated-society/
- https://www.charities.govt.nz/news-and-events/hot-topics/new-constitution-builder-tool-for-incorporated-societies/
- Hackland's latest official constitution: https://app.businessregisters.govt.nz/sber-businesses/viewInstance/view.html?id=229a78e05307b6d8bf1b29667f00cb17cc47efc6e28d8e3a#scrollTop
  - but looks like the laws for incorporated societies was changed in 2022, needs to be updated.

**Comment by ahdinosaur** [comment]
Did some research on charities, seems like we need a charitable purpose and the best option is one that fulfills ["Advancement of education"](https://www.charities.govt.nz/ready-to-register/need-to-know-to-register/charitable-purpose/advancement-of-education/).

Then I just asked ChatGPT, I'm annoyed that it's useful:

> To establish a hackerspace as an incorporated society with a charitable purpose in New Zealand, you could consider the following charitable purpose that aligns with New Zealand law:
>
> ### Charitable Purpose: **Advancement of Education through Technology and Innovation**
>
> **Purpose:**  
> The hackerspace will promote the advancement of education by providing a community space that fosters the learning and application of science, technology, engineering, and mathematics (STEM). The hackerspace will offer workshops, educational programs, and collaborative opportunities to support innovation, creativity, and skill development in areas such as coding, electronics, robotics, 3D printing, and digital fabrication.
>
> ---
>
> ### Explanation of Validity Under New Zealand Law
>
> In New Zealand, charitable purposes must fall under one or more of the following categories as defined by the Charities Act 2005:
>
> 1. **The relief of poverty:**
>   - This is not directly relevant to a hackerspace.
>   
> 2. **The advancement of education:**
>    - This is the most relevant category for a hackerspace. According to New Zealand law, the advancement of education includes activities that enhance knowledge and learning, as well as the dissemination of skills. A hackerspace that offers educational programs and opportunities for skill-building in technology clearly meets this criterion. The key is to ensure that these activities are structured to provide public benefit, rather than serving private or commercial interests.
>   
> 3. **The advancement of religion:**
>    - Not applicable.
>
> 4. **Other purposes beneficial to the community:**
>    - Hackerspaces also often serve this charitable purpose by creating a space where the community can engage with technology in a way that benefits society. For example, a hackerspace that encourages innovation and entrepreneurship or works to bridge the digital divide would also likely qualify under this category.
>
> For a hackerspace, focusing on **the advancement of education** will likely be the clearest and most valid charitable purpose. New Zealand law emphasizes that charitable organizations must provide a **public benefit**. A hackerspace offering educational workshops and resources open to the general public, especially targeting underserved communities or groups, would fulfill this requirement.
>
> In summary, by structuring the hackerspace’s activities around educational programs that provide learning opportunities in technology and innovation, you align the purpose with New Zealand’s legal framework for charitable organizations under the Charities Act 2005. Make sure to frame your activities in a way that benefits the broader community and does not prioritize private gain.

**Comment by ahdinosaur** [comment]
> The purposes of the Society are to:
> - Operate a community workshop that advances education and innovation in science, technology, engineering, mathematics and related fields.
> - Provide opportunities for people to share knowledge, tools and resources.
> - Do anything necessary or helpful to achieve these purposes.

**Comment by ahdinosaur** [comment]
> advancing education by... operating a community workshop to promote learning, creativity and skill development in science, technology, engineering, mathematics and other innovative fields.

**Comment by ahdinosaur** [comment]
made a draft:

- [2024.09.10 Draft Constitution.docx.pdf](https://github.com/user-attachments/files/16944015/2024.09.10.Draft.Constitution.docx.pdf)
- https://docs.google.com/document/d/1fiAd5wYt-Uf3AdzcyWngQ2_aLHeu-xJt/edit?usp=sharing&ouid=103379431023918171367&rtpof=true&sd=true

**Comment by irab** [comment]
Some good details on the process here:
https://menzshed.org.nz/wp-content/uploads/2024/07/Mens-Shed-Toolbox.pdf

**Comment by ahdinosaur** [comment]
wrote another revision of the charitable purpose:

> The Society is established and maintained exclusively for charitable purposes (including any purposes ancillary to those charitable purposes), namely:
>
> - providing premises in the Wellington district for anyone to have access to workshop facilities that enables them to share their knowledge, experiences and skills and work in harmony on projects for the benefit of the community or for their own personal benefit;
> - advancing education by offering workshops, educational activities, and collaborative opportunities that foster learning across a wide range of fields, including STEM (science, technology, engineering, mathematics), for the public benefit;
> - liaising with other organizations to promote the Society’s aims and enhance the positive impact on the community;
> - carrying out any other activities necessary or helpful to achieve the above charitable purposes.
>
> Any income, benefit, or advantage must be used to advance the charitable purposes of the Society
